### PR TITLE
Compare contents of existing files

### PR DESCRIPTION
**Pull request by rvagg**
Overhaul to make it compare the contents of existing files so help prevent file proliferation. Also added a `contentFn` callback to allow dynamic content generation rather than using a static file in the exercises directory because I need this for something I'm working on--it may also come in handy for i18n purposes so we don't have to duplicate the boilerplate files for each language.

Given the complexity of these changes, the pain of not having tests is increasing so I'm thinking that I probably need to spend some quality time introducing proper tests here before merging.

/cc @tdd @martinheidegger

### CODE REVIEW

**Comment by tdd** [comment]
Hey Rod,

This feature is def needed, especially in the multiple-`print` scenario.  I noticed the conspicuous absence of tests also in workshopper-* repos, we def need to address this.

I'll be focusing on L10n'ing / g11n'ing as many workshoppers as I can this week, in anticipation of the first [NodeSchool Paris](http://nodeschool.io/paris/) this Saturday. But I can help with tests after that. Do you know which framework/libs you're going with already? I personally favor Mocha, but anything solid's fine.

**Comment by rvagg** [comment]
I'd probably reach for tape to test this, _however_, I'm also a fan of the "first person to do the work gets to choose" rule, just like with code style within a project, same can generally go for dependencies (although there's potential for more substantive disagreement / discussion around the choice of dependencies than code style).

So how about this: I'd like to _try_ and get this PR sorted out and include tests along with it this week, but I'm usually so overloaded that I'm terrible at meeting those kinds of commitments. So, if you want to have a go then be my guest--the first person to PR some tests in gets to decide what test runner is used and how the tests are structured. Just make sure you PR early so we don't end up overlapping. If I end up dropping some tests in this PR I'll let you know.

**Comment by tdd** [comment]
Fine by me. I love Mocha but ecosystem plays a role here; for instance, stream-adventure uses tape, and as I intend to refactor it to use workshopper so it's easier to localize looking forward, staying with tape, especially as you like it too, looks like a good move.

I won't have time for tests this week anyhow, so your own PR stands a chance of first-posting :smile:

**Comment by rvagg** [comment]
Word of caution: perhaps don't put _too_ much work in to refactoring stream-adventure unless you're planning on doing a hard fork and publishing as something else. He probably would rather it be based on _adventure_ than _workshopper_. We have some fairly fundamental disagreements about how to build these things, hence the split in the ecosystem between _adventure_ and _workshopper_.

Probably worth persevering with the PR to get i18n into _adventure_ in either case. Hopefully all of these great translations of _workshopper_-based apps increases the pressure on that.

**Comment by tdd** [comment]
That's a good point. I'll probably try putting i18n, the `workshopper` way, in `adventure` first, in part to localize `javascripting`. Then I could offer to refactor `stream-adventure` based on the updated `adventure`. That would probably be smoother for all parties…

**Pull request closed without merging**
